# Generated by Django 5.2.7 on 2025-10-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sitesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
    ]
